# this is Makefile
# hello.out:max.o min.o hello.c
# in makefile, use tab=6 spaces
max_3.out:max1_3_notexe.o max_3.c
	  gcc max1_3_notexe.o max_3.c -o max_3.out
max1_3_notexe.o:max1_3.c
	  gcc -c max1_3.c -o max1_3_notexe.o

